# https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  webapp:
    build:
      target: production
    environment:
      - RAILS_ENV=production
      - MASTER_KEY=${MASTER_KEY}

  webserver:
    build:
      target: production
