# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3.9"

services:
  webapp:
    container_name: tinkerlog-web
    image: tylerlwsmith:tinkerlog
    restart: always
    build:
      context: ./webapp
      target: production
    environment:
      - RAILS_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./rails:/app
    depends_on:
      - database
    networks:
      - tinkerlog

  webserver:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  database:
    container_name: tinkerlog-db
    image: postgres:13.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - tinkerlog-database:/var/lib/postgresql/data
    networks:
      - tinkerlog

networks:
  tinkerlog:

volumes:
  tinkerlog-database:
